const REGULATION_TYPES = {
  'petroleum': 'Petroleum',
  'greenhouse_gas': 'Greenhouse gas'
};

const EXPLORATION_DEVELOPMENT_OPTIONS = {
  'exploration': 'Exploration',
  'development': 'Development'
};

const REVISION_TYPES = {
  '1': 'Significant modification or new stage of the activity (Regulation 17(5))',
  '2': 'New or increased environmental impact or risk (Regulation 17(6))',
  '3': 'Change in titleholder (Regulation 17(7))',
  '4': 'Revision on request of NOPSEMA (Regulation 18)',
  '5': 'Revision after a period of 5 years (Regulation 19)'
};

const LEVY_UNIT_VALUE = 4800;

const ACTIVITY_RATINGS = {
  '1001': 25,
  '1002': 14,
  '1003': 12,
  '1004': 6,
  '1005': 25,
  '1006': 16,
  '1007': 22,
  '1008': 16,
  '1009': 23,
  '1010': 16,
  '1011': 27,
  '1012': 17,
  '1013': 10,
  '1014': 9,
  '2001': 25,
  '2002': 12,
  '2003': 6,
  '2004': 25,
  '2005': 16,
  '2006': 22,
  '2007': 16,
  '2008': 23,
  '2009': 16,
  '2010': 27,
  '2011': 17,
  '2012': 10,
  '2013': 9
};

const COMPLIANCE_RATINGS = {
  '1001': 22,
  '1002': 9,
  '1003': 6,
  '1004': 3,
  '1005': 18,
  '1006': 13,
  '1007': 14,
  '1008': 14,
  '1009': 17,
  '1010': 13,
  '1011': 14,
  '1012': 9,
  '1013': 3,
  '1014': 3,
  '2001': 22,
  '2002': 6,
  '2003': 3,
  '2004': 18,
  '2005': 13,
  '2006': 14,
  '2007': 14,
  '2008': 17,
  '2009': 13,
  '2010': 14,
  '2011': 9,
  '2012': 3,
  '2013': 3
};

const PETROLEUM_ACTIVITY_TYPES = {
  '1001': 'Operation of a facility for the recovery or processing of petroleum',
  '1002': 'Storage of petroleum but not for the recovery or processing of petroleum',
  '1003': 'Recovery of Petroleum using subsea installation',
  '1004': 'Operation of a petroleum pipeline',
  '1005': 'Construction and installation of a facility',
  '1006': 'Construction and installation of a pipeline',
  '1007': 'Decommissioning, dismantling or removing a facility',
  '1008': 'Decommissioning, dismantling or removing a pipeline',
  '1009': 'Significant modification of a facility',
  '1010': 'Significant modification of a petroleum pipeline',
  '1011': 'Drilling',
  '1012': 'Seismic survey',
  '1013': 'Other survey',
  '1014': 'Any other petroleum-related activity'
};

const GREENHOUSE_GAS_ACTIVITY_TYPES = {
  '2001': 'Operation of a facility for the injection and storage of GHG substance',
  '2002': 'Injection of a GHG substance into the seabed/subsoil using a subsea installation',
  '2003': 'Operation of a greenhouse gas pipeline',
  '2004': 'Construction and installation of a facility',
  '2005': 'Construction and installation of a pipeline',
  '2006': 'Decommissioning, dismantling or removing a facility',
  '2007': 'Decommissioning, dismantling or removing a pipeline',
  '2008': 'Significant modification of a facility',
  '2009': 'Significant modification of a greenhouse gas pipeline',
  '2010': 'Drilling',
  '2011': 'Seismic survey',
  '2012': 'Other survey',
  '2013': 'Any other greenhouse gas-related activity'
};

const COUNTRIES = {
  "AF": "Afghanistan",
  "AX": "Åland Islands",
  "AL": "Albania",
  "DZ": "Algeria",
  "AS": "American Samoa",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AQ": "Antarctica",
  "AG": "Antigua and Barbuda",
  "AR": "Argentina",
  "AM": "Armenia",
  "AW": "Aruba",
  "AU": "Australia",
  "AT": "Austria",
  "AZ": "Azerbaijan",
  "BS": "Bahamas",
  "BH": "Bahrain",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Belarus",
  "BE": "Belgium",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Bhutan",
  "BO": "Bolivia, Plurinational State of",
  "BQ": "Bonaire, Sint Eustatius and Saba",
  "BA": "Bosnia and Herzegovina",
  "BW": "Botswana",
  "BV": "Bouvet Island",
  "BR": "Brazil",
  "IO": "British Indian Ocean Territory",
  "BN": "Brunei Darussalam",
  "BG": "Bulgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Cambodia",
  "CM": "Cameroon",
  "CA": "Canada",
  "CV": "Cape Verde",
  "KY": "Cayman Islands",
  "CF": "Central African Republic",
  "TD": "Chad",
  "CL": "Chile",
  "CN": "China",
  "CX": "Christmas Island",
  "CC": "Cocos (Keeling) Islands",
  "CO": "Colombia",
  "KM": "Comoros",
  "CG": "Congo",
  "CD": "Congo, the Democratic Republic of the",
  "CK": "Cook Islands",
  "CR": "Costa Rica",
  "CI": "Côte d'Ivoire",
  "HR": "Croatia",
  "CU": "Cuba",
  "CW": "Curaçao",
  "CY": "Cyprus",
  "CZ": "Czech Republic",
  "DK": "Denmark",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "EC": "Ecuador",
  "EG": "Egypt",
  "SV": "El Salvador",
  "GQ": "Equatorial Guinea",
  "ER": "Eritrea",
  "EE": "Estonia",
  "ET": "Ethiopia",
  "FK": "Falkland Islands (Malvinas)",
  "FO": "Faroe Islands",
  "FJ": "Fiji",
  "FI": "Finland",
  "FR": "France",
  "GF": "French Guiana",
  "PF": "French Polynesia",
  "TF": "French Southern Territories",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Georgia",
  "DE": "Germany",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Greece",
  "GL": "Greenland",
  "GD": "Grenada",
  "GP": "Guadeloupe",
  "GU": "Guam",
  "GT": "Guatemala",
  "GG": "Guernsey",
  "GN": "Guinea",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HM": "Heard Island and McDonald Mcdonald Islands",
  "VA": "Holy See (Vatican City State)",
  "HN": "Honduras",
  "HK": "Hong Kong",
  "HU": "Hungary",
  "IS": "Iceland",
  "IN": "India",
  "ID": "Indonesia",
  "IR": "Iran, Islamic Republic of",
  "IQ": "Iraq",
  "IE": "Ireland",
  "IM": "Isle of Man",
  "IL": "Israel",
  "IT": "Italy",
  "JM": "Jamaica",
  "JP": "Japan",
  "JE": "Jersey",
  "JO": "Jordan",
  "KZ": "Kazakhstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "KP": "Korea, Democratic People's Republic of",
  "KR": "Korea, Republic of",
  "KW": "Kuwait",
  "KG": "Kyrgyzstan",
  "LA": "Lao People's Democratic Republic",
  "LV": "Latvia",
  "LB": "Lebanon",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libya",
  "LI": "Liechtenstein",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "MO": "Macao",
  "MK": "Macedonia, the Former Yugoslav Republic of",
  "MG": "Madagascar",
  "MW": "Malawi",
  "MY": "Malaysia",
  "MV": "Maldives",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshall Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "YT": "Mayotte",
  "MX": "Mexico",
  "FM": "Micronesia, Federated States of",
  "MD": "Moldova, Republic of",
  "MC": "Monaco",
  "MN": "Mongolia",
  "ME": "Montenegro",
  "MS": "Montserrat",
  "MA": "Morocco",
  "MZ": "Mozambique",
  "MM": "Myanmar",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Netherlands",
  "NC": "New Caledonia",
  "NZ": "New Zealand",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NU": "Niue",
  "NF": "Norfolk Island",
  "MP": "Northern Mariana Islands",
  "NO": "Norway",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Palestine, State of",
  "PA": "Panama",
  "PG": "Papua New Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Philippines",
  "PN": "Pitcairn",
  "PL": "Poland",
  "PT": "Portugal",
  "PR": "Puerto Rico",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Romania",
  "RU": "Russian Federation",
  "RW": "Rwanda",
  "BL": "Saint Barthélemy",
  "SH": "Saint Helena, Ascension and Tristan da Cunha",
  "KN": "Saint Kitts and Nevis",
  "LC": "Saint Lucia",
  "MF": "Saint Martin (French part)",
  "PM": "Saint Pierre and Miquelon",
  "VC": "Saint Vincent and the Grenadines",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "Sao Tome and Principe",
  "SA": "Saudi Arabia",
  "SN": "Senegal",
  "RS": "Serbia",
  "SC": "Seychelles",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SX": "Sint Maarten (Dutch part)",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "SB": "Solomon Islands",
  "SO": "Somalia",
  "ZA": "South Africa",
  "GS": "South Georgia and the South Sandwich Islands",
  "SS": "South Sudan",
  "ES": "Spain",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Suriname",
  "SJ": "Svalbard and Jan Mayen",
  "SZ": "Swaziland",
  "SE": "Sweden",
  "CH": "Switzerland",
  "SY": "Syrian Arab Republic",
  "TW": "Taiwan, Province of China",
  "TJ": "Tajikistan",
  "TZ": "Tanzania, United Republic of",
  "TH": "Thailand",
  "TL": "Timor-Leste",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad and Tobago",
  "TN": "Tunisia",
  "TR": "Turkey",
  "TM": "Turkmenistan",
  "TC": "Turks and Caicos Islands",
  "TV": "Tuvalu",
  "UG": "Uganda",
  "UA": "Ukraine",
  "AE": "United Arab Emirates",
  "GB": "United Kingdom",
  "US": "United States",
  "UM": "United States Minor Outlying Islands",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VE": "Venezuela, Bolivarian Republic of",
  "VN": "Viet Nam",
  "VG": "Virgin Islands, British",
  "VI": "Virgin Islands, U.S.",
  "WF": "Wallis and Futuna",
  "EH": "Western Sahara",
  "YE": "Yemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
};

const DECLARATION_OPTIONS = {
  declarationOption1: 'Only one registered titleholder',
  declarationOption2: 'Multiple titleholders',
  declarationOption3: 'Multiple titleholders and the financial assurance obligations are to be discharged by a single entity'
};

const SIGNATORY_TYPES = {
  signatoryType1: 'A company director, authorised officer or individual with the registered titleholders express or implied authority and on behalf of the titleholder',
  signatoryType2: 'A person appointed under power of attorney on behalf of the titleholder'
};

const CONFIRMATION_METHODS = {
  calculationMethod1: 'APPEA method',
  calculationMethod2: 'Other endorsed method'
};

export default {
  REGULATION_TYPES,
  REVISION_TYPES,
  PETROLEUM_ACTIVITY_TYPES,
  GREENHOUSE_GAS_ACTIVITY_TYPES,
  COUNTRIES,
  ACTIVITY_RATINGS,
  COMPLIANCE_RATINGS,
  LEVY_UNIT_VALUE,
  DECLARATION_OPTIONS,
  SIGNATORY_TYPES,
  CONFIRMATION_METHODS,
  EXPLORATION_DEVELOPMENT_OPTIONS
};
